# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       xserver-policy-enforcement

# >> macros
# << macros

Summary:    Interface between Xserver Policy Enforcement and Policy Decision
Version:    0.0.2
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://meego.gitorious.org/maemo-multimedia/xserver-policy-enforcement
Source0:    %{name}-%{version}.tar.gz
Source100:  xserver-policy-enforcement.yaml
Patch0:     noauth-for-root.patch
Patch1:     make-the-verbosity-level-of-trace-messages-higher.patch
Patch2:     0001-Remove-usage-of-client-states-that-have-been-dropped.patch
Patch3:     0002-swaps-and-swapl-take-only-one-argument-anymore.patch
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xorg-server)

%description
Interface between Xserver Policy Enforcement and Policy Decision. | Does video routing.

%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.

%prep
%setup -q -n %{name}-%{version}

# noauth-for-root.patch
%patch0 -p1
# make-the-verbosity-level-of-trace-messages-higher.patch
%patch1 -p1
# 0001-Remove-usage-of-client-states-that-have-been-dropped.patch
%patch2 -p1
# 0002-swaps-and-swapl-take-only-one-argument-anymore.patch
%patch3 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/videoipc-client
%config %{_sysconfdir}/X11/xorg.conf.d/policy.conf
%{_sysconfdir}/xdg/autostart/xserver-policy-enforcement.desktop
%{_libdir}/xorg/modules/extensions/libpolicy.so
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/policy
%{_libdir}/pkgconfig/*.pc
# << files devel
